server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

spring:
  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
    hibernate:
      ddl-auto: create
